### ISSUE TITLE
Add Support For `clangd`

### ISSUE THREAD

**Issue by josephattalla** [anurag3301/nvim-platformio.lua#17]
Initializing creates a `.ccls` file, but I use `clangd`. To have my LSP work correctly I run `pio run -t compiledb` which creates a `compile_commands.json` file. It would be nice if there were an option to create this automatically when running `Pioinit`.

**Comment by anurag3301** [comment]
Hey @josephattalla I just pushed a commit which addes a `setup` funtion which you can call from you neovim configuration. There you can set your lsp to `clangd` which is by defalult `ccls`. If you pick `clangd` it automatically   calles `pio run -t compiledb` and create the `compile_commands.json` file.

```lua
require('platformio').setup({
    lsp = "ccls" --default: ccls, other option: clangd
                 -- If you pick clangd, it also creates compile_commands.json
})
```

Let me know if it works for you

**Comment by josephattalla** [comment]
Works, thanks

**Comment by anurag3301** [comment]
Hey @karshPrime  The plugin already generates `compile_commands.json` when you chose clangd as you lsp in config for this plugin.
