### ISSUE TITLE
Addding tables for the commands usage

### ISSUE THREAD

**Issue by dhupee** [anurag3301/nvim-platformio.lua#2]
Since the commands use short word like lib, mon, cmd I think it's a good idea to elaborate the meaning or usage of the commands

**Comment by anurag3301** [comment]
I have actually added it in as a vim doc, try `:h PlatformIO` or check [doc/platformio.txt
](https://github.com/anurag3301/nvim-platformio.lua/blob/main/doc/platformio.txt)

If you meant something else, let me know.

**Comment by anurag3301** [comment]
Though docs are kind of broken, like I get `E434: Can't find tag pattern` when I run `:h PlatformIO` or `:h :Piorun` dont work at all. I'll check how its setup in other projects and fix mine too.

**Comment by anurag3301** [comment]
Closing. PR #3
