### ISSUE TITLE
[Feature request] Is there any possibility for Windows support?

### ISSUE THREAD

**Issue by Rumi152** [anurag3301/nvim-platformio.lua#5]
Right now every command throws errors, even after i have fixed some of them in source. I suppose it is fully Windows incompatible?

**Comment by anurag3301** [comment]
Hey @Rumi152, yes I have not tested it on windows, Probably will do it later. But it should work provided `pio` is in path. Will have check how toggleterm works on windows.

**Comment by anurag3301** [comment]
Hey @Rumi152, windows support has been added with #7 PR and I have tested it

**Comment by Rumi152** [comment]
Ok. Thanks for this great plugin.
