### ISSUE TITLE
Error loading with Packer

### ISSUE THREAD

**Issue by Erickrgb22** [anurag3301/nvim-platformio.lua#6]
Hi, i installed via Packer like the README says but when i execute any of the available commands, like Pioinit for example neovim gives me this error: 

![image](https://github.com/anurag3301/nvim-platformio.lua/assets/45826601/c008ff87-4a50-4fab-863a-163a45f4b97f)

Here is my packer.lua

![image](https://github.com/anurag3301/nvim-platformio.lua/assets/45826601/e2df3c9d-54eb-4b0f-91b6-4e0289cefaad)

Its any bad with my configs? or its really a bug or something weird?

**Comment by anurag3301** [comment]
Hey @Erickrgb22 I forgot about this issue. Are you still facing this issue?

**Comment by braedonwatkins** [comment]
I got this on my initial run but running again seemed to work. If it happens again I'll give more detailed info.

**Comment by anurag3301** [comment]
Alr, closing the issue
